<section class="components-page cards-showcase cards-actions-page">
  <section class="component-section">
    <div class="card app-card">
      <div class="card-header"><h5 class="card-title mb-0">Cards Action</h5></div>
      <div class="table-responsive"><table class="table app-table mb-0"><thead><tr><th>Action</th><th>Icon</th><th>Details</th></tr></thead><tbody><tr><td>Collapse</td><td><i class="bi bi-chevron-up"></i></td><td>Collapse card content using a collapse action.</td></tr><tr><td>Refresh Content</td><td><i class="bi bi-arrow-clockwise"></i></td><td>Refresh card content using a refresh action.</td></tr><tr><td>Expand Card</td><td><i class="bi bi-arrows-fullscreen"></i></td><td>Maximize your card using an expand action.</td></tr><tr><td>Remove Card</td><td><i class="bi bi-x-lg"></i></td><td>Remove card from page using a close action.</td></tr></tbody></table></div>
    </div>
  </section>

  <section class="component-section">
    <h5 class="component-heading">Examples</h5>
    <p class="text-app-secondary">Use action buttons in the card header to show static examples of the same interaction patterns.</p>
    <div class="row g-3">
      <div class="col-md-6 col-xl-3"><div class="card app-card h-100"><div class="card-header app-card-header"><h6 class="mb-0">Collapsible Card</h6><button class="btn btn-light btn-icon btn-sm" type="button" aria-label="Collapse card"><i class="bi bi-chevron-up"></i></button></div><div class="card-body"><p class="text-app-secondary mb-0">Click on the collapse icon in a full implementation to hide or show content.</p></div></div></div>
      <div class="col-md-6 col-xl-3"><div class="card app-card h-100"><div class="card-header app-card-header"><h6 class="mb-0">Refresh Content</h6><button class="btn btn-light btn-icon btn-sm" type="button" aria-label="Refresh card"><i class="bi bi-arrow-clockwise"></i></button></div><div class="card-body"><p class="text-app-secondary mb-0">Use a card alert or loading state when content is refreshed.</p></div></div></div>
      <div class="col-md-6 col-xl-3"><div class="card app-card h-100"><div class="card-header app-card-header"><h6 class="mb-0">Expand Card</h6><button class="btn btn-light btn-icon btn-sm" type="button" aria-label="Expand card"><i class="bi bi-arrows-fullscreen"></i></button></div><div class="card-body"><p class="text-app-secondary mb-0">Fullscreen action can make detailed content easier to inspect.</p></div></div></div>
      <div class="col-md-6 col-xl-3"><div class="card app-card h-100"><div class="card-header app-card-header"><h6 class="mb-0">Remove Card</h6><button class="btn btn-light btn-icon btn-sm" type="button" aria-label="Remove card"><i class="bi bi-x-lg"></i></button></div><div class="card-body"><p class="text-app-secondary mb-0">Close action removes the card from the visible workspace.</p></div></div></div>
    </div>
  </section>

  <section class="component-section">
    <h5 class="component-heading">Header Elements</h5>
    <div class="row g-3">
      <div class="col-md-6 col-xl-4"><div class="card app-card h-100"><div class="card-header app-card-header"><span>Card Header</span><span class="badge badge-soft-primary">New</span></div><div class="card-body"><h5 class="card-title">Card Title</h5><p class="text-app-secondary mb-0">Sample card header with badge.</p></div></div></div>
      <div class="col-md-6 col-xl-4"><div class="card app-card h-100"><div class="card-header app-card-header"><h5 class="card-title mb-0">Card Title</h5><span class="badge rounded-pill text-bg-primary">10</span></div><div class="card-body"><p class="text-app-secondary mb-0">Sample card title with outline badge.</p></div></div></div>
      <div class="col-md-6 col-xl-4"><div class="card app-card h-100"><div class="card-header app-card-header"><span>Card Header</span><button class="btn btn-primary btn-sm" type="button">Button</button></div><div class="card-body"><p class="text-app-secondary mb-0">Sample card header with extra small button.</p></div></div></div>
      <div class="col-md-6 col-xl-4"><div class="card app-card h-100"><div class="card-header app-card-header"><h5 class="card-title mb-0">Card Title</h5><button class="btn btn-light btn-icon btn-sm" type="button" aria-label="Settings"><i class="bi bi-gear"></i></button></div><div class="card-body"><p class="text-app-secondary mb-0">Sample card title with small icon button.</p></div></div></div>
      <div class="col-md-6 col-xl-4"><div class="card app-card h-100"><div class="card-header app-card-header"><span>Card Header</span><div class="topbar-search cards-header-search"><i class="bi bi-search"></i><input type="search" placeholder="Search" aria-label="Search card"></div></div><div class="card-body"><p class="text-app-secondary mb-0">Sample card header with extra search input box.</p></div></div></div>
      <div class="col-md-6 col-xl-4"><div class="card app-card h-100"><div class="card-header app-card-header"><h5 class="card-title mb-0">Card Title</h5><div class="form-check form-switch mb-0"><input class="form-check-input" type="checkbox" role="switch" checked aria-label="Toggle card"></div></div><div class="card-body"><p class="text-app-secondary mb-0">Sample card title with switch.</p></div></div></div>
      <div class="col-md-6 col-xl-4"><div class="card app-card h-100"><div class="card-header app-card-header"><span>Card Header</span><span class="text-app-secondary">Sample Text</span></div><div class="card-body"><h5 class="card-title">Card Title</h5><p class="text-app-secondary mb-0">Sample card header with text.</p></div></div></div>
      <div class="col-md-6 col-xl-4"><div class="card app-card h-100"><div class="card-header app-card-header"><h5 class="card-title mb-0">Card Title</h5><span class="text-app-secondary">Sample Text</span></div><div class="card-body"><p class="text-app-secondary mb-0">Sample card title with text.</p></div></div></div>
      <div class="col-md-6 col-xl-4"><div class="card app-card h-100"><div class="card-header app-card-header"><div><span>Card Header</span><h5 class="card-title mb-0">Hello!</h5></div><div class="dropdown"><button class="btn btn-primary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown">Primary</button><ul class="dropdown-menu dropdown-menu-end"><li><a class="dropdown-item" href="coming-soon.php">Action</a></li><li><a class="dropdown-item" href="coming-soon.php">Another action</a></li><li><a class="dropdown-item" href="coming-soon.php">Something else here</a></li><li><hr class="dropdown-divider"></li><li><a class="dropdown-item" href="coming-soon.php">Separated link</a></li></ul></div></div><div class="card-body"><p class="text-app-secondary mb-0">Sample card header with badge and dropdown.</p></div></div></div>
      <div class="col-12"><div class="card app-card"><div class="card-header app-card-header"><h5 class="card-title mb-0">Card Title</h5><div class="cards-header-controls"><div class="form-check form-switch mb-0"><input class="form-check-input" type="checkbox" role="switch" checked aria-label="Header switch"></div><select class="form-select form-select-sm" aria-label="Header select"><option>Select</option><option>Option A</option></select><button class="btn btn-primary btn-sm" type="button">Go</button></div></div><div class="card-body"><p class="text-app-secondary mb-0">Sample card title with switch, select box and button.</p></div></div></div>
    </div>
  </section>

  <section class="component-section">
    <h5 class="component-heading">Draggable Cards</h5>
    <div class="row g-3">
      <div class="col-md-6 col-xl-4"><div class="card cards-solid cards-solid-primary"><div class="card-header app-card-header"><span>Drag me!</span><i class="bi bi-grip-vertical"></i></div><div class="card-body"><h5 class="card-title">Primary card title</h5><p class="card-text">Some quick example text to build on the card title and make up.</p></div></div></div>
      <div class="col-md-6 col-xl-4"><div class="card cards-solid cards-solid-secondary"><div class="card-header app-card-header"><span>Drag me!</span><i class="bi bi-grip-vertical"></i></div><div class="card-body"><h5 class="card-title">Secondary card title</h5><p class="card-text">Some quick example text to build on the card title and make up.</p></div></div></div>
      <div class="col-md-6 col-xl-4"><div class="card cards-solid cards-solid-success"><div class="card-header app-card-header"><span>Drag me!</span><i class="bi bi-grip-vertical"></i></div><div class="card-body"><h5 class="card-title">Success card title</h5><p class="card-text">Some quick example text to build on the card title and make up.</p></div></div></div>
      <div class="col-md-6 col-xl-4"><div class="card cards-solid cards-solid-danger"><div class="card-header app-card-header"><span>Drag me!</span><i class="bi bi-grip-vertical"></i></div><div class="card-body"><h5 class="card-title">Danger card title</h5><p class="card-text">Some quick example text to build on the card title and make up.</p></div></div></div>
      <div class="col-md-6 col-xl-4"><div class="card cards-solid cards-solid-warning"><div class="card-header app-card-header"><span>Drag me!</span><i class="bi bi-grip-vertical"></i></div><div class="card-body"><h5 class="card-title">Warning card title</h5><p class="card-text">Some quick example text to build on the card title and make up.</p></div></div></div>
      <div class="col-md-6 col-xl-4"><div class="card cards-solid cards-solid-info"><div class="card-header app-card-header"><span>Drag me!</span><i class="bi bi-grip-vertical"></i></div><div class="card-body"><h5 class="card-title">Info card title</h5><p class="card-text">Some quick example text to build on the card title and make up.</p></div></div></div>
    </div>
  </section>
</section>
