<section class="components-page form-elements-page">
  <div class="row g-4">
    <div class="col-xl-6"><div class="card app-card component-section"><div class="card-header"><h5 class="card-title mb-0">Basic</h5></div><div class="card-body form-stack"><div class="input-group"><span class="input-group-text" id="basicAddon1">@</span><input type="text" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="basicAddon1"></div><div class="input-group"><input type="text" class="form-control" placeholder="Recipient's username" aria-label="Recipient username"><span class="input-group-text">@example.com</span></div><label class="form-label mb-0">Your vanity URL</label><div class="input-group"><span class="input-group-text">example.com/users/</span><input type="text" class="form-control" placeholder="username"></div><div class="input-group"><span class="input-group-text">$</span><input type="text" class="form-control" placeholder="Amount"><span class="input-group-text">.00</span></div></div></div></div>
    <div class="col-xl-6"><div class="card app-card component-section"><div class="card-header"><h5 class="card-title mb-0">Sizing</h5></div><div class="card-body form-stack"><div class="input-group input-group-lg"><span class="input-group-text">Large</span><input type="text" class="form-control"></div><div class="input-group"><span class="input-group-text">Default</span><input type="text" class="form-control"></div><div class="input-group input-group-sm"><span class="input-group-text">Small</span><input type="text" class="form-control"></div></div></div></div>
  </div>

  <div class="row g-4">
    <div class="col-xl-6"><div class="card app-card component-section"><div class="card-header"><h5 class="card-title mb-0">Checkboxes & Radios</h5></div><div class="card-body form-stack"><div class="input-group"><div class="input-group-text"><input class="form-check-input mt-0" type="checkbox" aria-label="Checkbox for input group"></div><input type="text" class="form-control" aria-label="Text input with checkbox"></div><div class="input-group"><div class="input-group-text"><input class="form-check-input mt-0" type="radio" aria-label="Radio button for input group"></div><input type="text" class="form-control" aria-label="Text input with radio button"></div></div></div></div>
    <div class="col-xl-6"><div class="card app-card component-section"><div class="card-header"><h5 class="card-title mb-0">Multiple Addons</h5></div><div class="card-body form-stack"><div class="input-group"><span class="input-group-text">First and last name</span><input type="text" aria-label="First name" class="form-control"><input type="text" aria-label="Last name" class="form-control"></div><div class="input-group"><span class="input-group-text">With textarea</span><textarea class="form-control" aria-label="With textarea"></textarea></div></div></div></div>
  </div>

  <div class="card app-card component-section"><div class="card-header"><h5 class="card-title mb-0">Button Addons & Dropdowns</h5></div><div class="card-body form-stack"><div class="input-group"><button class="btn btn-outline-primary" type="button">Button</button><input type="text" class="form-control" placeholder="Button addon"></div><div class="input-group"><input type="text" class="form-control" placeholder="Search invoice"><button class="btn btn-primary" type="button"><i class="bi bi-search me-1"></i>Search</button></div><div class="input-group"><button class="btn btn-outline-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</button><ul class="dropdown-menu"><li><a class="dropdown-item" href="coming-soon.php">Action</a></li><li><a class="dropdown-item" href="coming-soon.php">Another action</a></li><li><a class="dropdown-item" href="coming-soon.php">Something else here</a></li></ul><input type="text" class="form-control" aria-label="Text input with dropdown button"></div></div></div>
</section>